### ISSUE TITLE
Payment Method Not showing up immediately on Example

### ISSUE THREAD

**Issue by femidof** [a11rew/medusa-payment-paystack#137] opened 2024-05-11 00:19 UTC
Hi, I was testing out your hosted demo. There seems to be an error when the address is filled in and delivery is selected. The options for the payment doesn't show up immediately, but the hack was to try edit the form again and the payment shows up.

I have the exact same error after integrating my frontend as well, on the browser log I found found the attached below but I do not know exactly where this error is. For some reason im thinking it has to do with state 

<img width="567" alt="Screenshot 2024-05-10 at 7 15 56 PM" src="https://github.com/a11rew/medusa-payment-paystack/assets/42376175/fc4b6f88-a1af-4a0a-9eb4-ac6ac01baff0">

**Comment by a11rew** [comment] 2024-05-11 19:51
I was able to reproduce this on Safari. Looks like an issue with the React state updates applied after clicking the "Continue to payment" button in the Delivery section.

The [changes in this commit](https://github.com/a11rew/medusa-payment-paystack/commit/6c21dfe204a57603e7c7bb3c7d4f9eef96d7b9b4) fixed it in my reproduction. Specifically using `flushSync` for the state updates. Try those changes and let me know if it fixes it for you too. Will get it merged into the example if it does.

**Comment by femidof** [comment] 2024-05-15 06:17
Thanks for the update, it did work. I really appreciate the response

**Closed** 2024-05-15 08:57 UTC
